mqtt_broker:
  host: "xxx"
  port: "xxxx"
  port_for_websocket: "xxxx"

etcd_cluster:
  endpoints: [ "xxx.xxx.xxx:xxxx", "xxx.xxx.xxx:xxxx", "xxx.xxx.xxx:xxxx" ]

admin_web:
  host: "xxx"
  port: "xxx"